core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('w3music.urls', namespace='w3music')),
]

w3music/urls.py
from django.urls import path
from w3music import w3music_views

app_name='w3music'
urlpatterns = [
    
    # path('',w3music_views.index,name="index"),
    path('',w3music_views.index,name="index"),
    path('index-2/',w3music_views.index_2,name="index-2"),
    path('index-3/',w3music_views.index_3,name="index-3"),
    path('index-4/',w3music_views.index_4,name="index-4"),

    path('about-us/',w3music_views.about_us,name="about-us"),
    path('about-me/',w3music_views.about_me,name="about-me"),
    path('faqs/',w3music_views.faqs,name="faqs"),
    path('tickets/',w3music_views.tickets,name="tickets"),
    path('team/',w3music_views.team,name="team"),
    path('artists-list/',w3music_views.artists_list,name="artists-list"),
    path('artists-single/',w3music_views.artists_single,name="artists-single"),
    path('services/',w3music_views.services,name="services"),
    path('events/',w3music_views.events,name="events"),
    path('events-list/',w3music_views.events_list,name="events-list"),
    path('events-table/',w3music_views.events_table,name="events-table"),
    path('events-detail/',w3music_views.events_detail,name="events-detail"),

    path('compact-album-single/',w3music_views.compact_album_single,name="compact-album-single"),
    path('minimal-album-single/',w3music_views.minimal_album_single,name="minimal-album-single"),
    path('gallery-2-columns/',w3music_views.gallery_2_columns,name="gallery-2-columns"),
    path('gallery-3-columns/',w3music_views.gallery_3_columns,name="gallery-3-columns"),
    path('gallery-4-columns/',w3music_views.gallery_4_columns,name="gallery-4-columns"),
    path('gallery-4-columns-wide/',w3music_views.gallery_4_columns_wide,name="gallery-4-columns-wide"),
    path('gallery-5-columns-wide/',w3music_views.gallery_5_columns_wide,name="gallery-5-columns-wide"),
    path('standard-2-columns/',w3music_views.standard_2_columns,name="standard-2-columns"),
    path('standard-3-columns/',w3music_views.standard_3_columns,name="standard-3-columns"),
    path('standard-4-columns/',w3music_views.standard_4_columns,name="standard-4-columns"),
    path('standard-4-columns-wide/',w3music_views.standard_4_columns_wide,name="standard-4-columns-wide"),
    path('standard-5-columns-wide/',w3music_views.standard_5_columns_wide,name="standard-5-columns-wide"),
    path('error-404/',w3music_views.error_404,name="error-404"),
    path('under-maintenance/',w3music_views.under_maintenance,name="under-maintenance"),
    path('coming-soon/',w3music_views.coming_soon,name="coming-soon"),

    path('shop-cart/',w3music_views.shop_cart,name="shop-cart"),
    path('shop-wishlist/',w3music_views.shop_wishlist,name="shop-wishlist"),
    path('shop-checkout/',w3music_views.shop_checkout,name="shop-checkout"),
    path('shop-my-account/',w3music_views.shop_my_account,name="shop-my-account"),
    path('shop-registration/',w3music_views.shop_registration,name="shop-registration"),
    path('product-detail/',w3music_views.product_detail,name="product-detail"),
    path('shop-sidebar/',w3music_views.shop_sidebar,name="shop-sidebar"),
    path('shop-3-column/',w3music_views.shop_3_column,name="shop-3-column"),
    path('shop-4-column/',w3music_views.shop_4_column,name="shop-4-column"),
    path('shop-wide-4-column/',w3music_views.shop_wide_4_column,name="shop-wide-4-column"),

    path('blog-grid-left-sidebar/',w3music_views.blog_grid_left_sidebar,name="blog-grid-left-sidebar"),
    path('blog-grid-right-sidebar/',w3music_views.blog_grid_right_sidebar,name="blog-grid-right-sidebar"),
    path('blog-list-left-sidebar/',w3music_views.blog_list_left_sidebar,name="blog-list-left-sidebar"),
    path('blog-list-right-sidebar/',w3music_views.blog_list_right_sidebar,name="blog-list-right-sidebar"),
    path('blog-detail-left-sidebar/',w3music_views.blog_detail_left_sidebar,name="blog-detail-left-sidebar"),
    path('blog-detail-right-sidebar/',w3music_views.blog_detail_right_sidebar,name="blog-detail-right-sidebar"),
    path('blog-grid/',w3music_views.blog_grid,name="blog-grid"),
    path('blog-large-left-sidebar/',w3music_views.blog_large_left_sidebar,name="blog-large-left-sidebar"),
    path('blog-list/',w3music_views.blog_list,name="blog-list"),
    path('blog-grid-2/',w3music_views.blog_grid_2,name="blog-grid-2"),
    path('blog-grid-3/',w3music_views.blog_grid_3,name="blog-grid-3"),
    path('blog-details/',w3music_views.blog_details,name="blog-details"),
    path('blog-open-gutenberg/',w3music_views.blog_open_gutenberg,name="blog-open-gutenberg"),
    path('blog-standard/',w3music_views.blog_standard,name="blog-standard"),
    path('blog-grid-3-masonary/',w3music_views.blog_grid_3_masonary,name="blog-grid-3-masonary"),
    path('blog-grid-4-masonary/',w3music_views.blog_grid_4_masonary,name="blog-grid-4-masonary"),
    path('blog-wide-grid-sidebar/',w3music_views.blog_wide_grid_sidebar,name="blog-wide-grid-sidebar"),
    path('blog-wide-list-sidebar/',w3music_views.blog_wide_list_sidebar,name="blog-wide-list-sidebar"),
    
    path('contact-us/',w3music_views.contact_us,name="contact-us"),

]

w3music/models.py
from django.db import models

# Create your models here.

w3music/views.py
from django.shortcuts import render

# Create your views here.

templates/w3music/blog-list.html
{% extends 'w3music/elements/layouts/layout.html' %}
{% load static %}
        
{% block additional_css %}
{% endblock %}
		
{% block content %}
		<!-- Blog Section -->
		<section class="content-inner-1">
			<div class="min-container">
				<div class="row loadmore-content">
					<div class="col-xl-12 col-lg-12">
						<div class="dz-card style-1 overlay-shine blog-half dz-img-effect zoom m-b30">
							<div class="dz-media">
								<a href="{% url 'w3music:blog-details' %}"><img src="{% static 'w3music/images/blog/grid/pic1.jpg' %}" alt="/"></a>
							</div>
							<div class="dz-info">
								<div class="dz-meta">
									<ul>
										<li class="dz-comment"><a href="javascript:void(0);">0 Comment</a></li>
										<li><a href="javascript:void(0);">Sep 10, 2023</a></li>
									</ul>
								</div> 
								<h5 class="dz-title"><a href="{% url 'w3music:blog-details' %}">Tuning an Acoustic and Electric Guitar in 6 Steps</a></h5>
								<p>Lorem Ipsum is simply dummy text of has the printing and has been typesetting industry. </p>
								<div class="read-btn">
									<a href="{% url 'w3music:blog-details' %}" class="btn btn-dark rounded-0 btn-hover-2 text-uppercase">read more</a>
								</div>
							</div>
						</div>
					</div>
					<div class="col-xl-12 col-lg-12">
						<div class="dz-card style-1 overlay-shine blog-half dz-img-effect zoom m-b30">
							<div class="dz-media">
								<a href="{% url 'w3music:blog-details' %}"><img src="{% static 'w3music/images/blog/grid/pic2.jpg' %}" alt="/"></a>
							</div>
							<div class="dz-info">
								<div class="dz-meta">
									<ul>
										<li class="dz-comment"><a href="javascript:void(0);">1 Comment</a></li>
										<li><a href="javascript:void(0);">Jun 16, 2023</a></li>
									</ul>
								</div> 
								<h5 class="dz-title"><a href="{% url 'w3music:blog-details' %}">Must-haves in your 2023 playlist.</a></h5>
								<p>Lorem Ipsum is simply dummy text of has the printing and has been typesetting industry. </p>
								<div class="read-btn">
									<a href="{% url 'w3music:blog-details' %}" class="btn btn-dark rounded-0 btn-hover-2 text-uppercase">read more</a>
								</div>
							</div>
						</div>
					</div>
					<div class="col-xl-12 col-lg-12">
						<div class="dz-card style-1 overlay-shine blog-half dz-img-effect zoom m-b30">
							<div class="dz-media">
								<a href="{% url 'w3music:blog-details' %}"><img src="{% static 'w3music/images/blog/grid/pic3.jpg' %}" alt="/"></a>
							</div>
							<div class="dz-info">
								<div class="dz-meta">
									<ul>
										<li class="dz-comment"><a href="javascript:void(0);">2 Comment</a></li>
										<li><a href="javascript:void(0);">Apr 22, 2023</a></li>
									</ul>
								</div> 
								<h5 class="dz-title"><a href="{% url 'w3music:blog-details' %}">Behind the Scenes of the Music World</a></h5>
								<p>Lorem Ipsum is simply dummy text of has the printing and has been typesetting industry. </p>
								<div class="read-btn">
									<a href="{% url 'w3music:blog-details' %}" class="btn btn-dark rounded-0 btn-hover-2 text-uppercase">read more</a>
								</div>
							</div>
						</div>
					</div>
					<div class="col-xl-12 col-lg-12">
						<div class="dz-card style-1 overlay-shine blog-half dz-img-effect zoom m-b30">
							<div class="dz-media">
								<a href="{% url 'w3music:blog-details' %}"><img src="{% static 'w3music/images/blog/grid/pic4.jpg' %}" alt="/"></a>
							</div>
							<div class="dz-info">
								<div class="dz-meta">
									<ul>
										<li class="dz-comment"><a href="javascript:void(0);">6 Comment</a></li>
										<li><a href="javascript:void(0);">May 19, 2023</a></li>
									</ul>
								</div> 
								<h5 class="dz-title"><a href="{% url 'w3music:blog-details' %}">Musings on Music's Emotional Impact</a></h5>
								<p>Lorem Ipsum is simply dummy text of has the printing and has been typesetting industry. </p>
								<div class="read-btn">
									<a href="{% url 'w3music:blog-details' %}" class="btn btn-dark rounded-0 btn-hover-2 text-uppercase">read more</a>
								</div>
							</div>
						</div>
					</div>
					<div class="col-xl-12 col-lg-12">
						<div class="dz-card style-1 overlay-shine blog-half dz-img-effect zoom m-b30">
							<div class="dz-media">
								<a href="{% url 'w3music:blog-details' %}"><img src="{% static 'w3music/images/blog/grid/pic5.jpg' %}" alt="/"></a>
							</div>
							<div class="dz-info">
								<div class="dz-meta">
									<ul>
										<li class="dz-comment"><a href="javascript:void(0);">5 Comment</a></li>
										<li><a href="javascript:void(0);">Jan 29, 2023</a></li>
									</ul>
								</div> 
								<h5 class="dz-title"><a href="{% url 'w3music:blog-details' %}">Exploring Music's Many Dimensions</a></h5>
								<p>Lorem Ipsum is simply dummy text of has the printing and has been typesetting industry. </p>
								<div class="read-btn">
									<a href="{% url 'w3music:blog-details' %}" class="btn btn-dark rounded-0 btn-hover-2 text-uppercase">read more</a>
								</div>
							</div>
						</div>
					</div>
					<div class="col-xl-12 col-lg-12">
						<div class="dz-card style-1 overlay-shine blog-half dz-img-effect zoom m-b30">
							<div class="dz-media">
								<a href="{% url 'w3music:blog-details' %}"><img src="{% static 'w3music/images/blog/grid/pic6.jpg' %}" alt="/"></a>
							</div>
							<div class="dz-info">
								<div class="dz-meta">
									<ul>
										<li class="dz-comment"><a href="javascript:void(0);">7 Comment</a></li>
										<li><a href="javascript:void(0);">Jan 5, 2023</a></li>
									</ul>
								</div> 
								<h5 class="dz-title"><a href="{% url 'w3music:blog-details' %}">All The Great songs have been written.</a></h5>
								<p>Lorem Ipsum is simply dummy text of has the printing and has been typesetting industry. </p>
								<div class="read-btn">
									<a href="{% url 'w3music:blog-details' %}" class="btn btn-dark rounded-0 btn-hover-2 text-uppercase">read more</a>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="text-center m-t10">
					<a class="btn btn-dark rounded-0 dz-load-more btn-hover-2" href="javascript:void(0);" rel="/static/w3music/ajax/blog-list.html">Load More</a>
				</div>
			</div>
		</section>
		<!-- Blog Section -->
{% endblock %}

templates/w3music/elements/banner.html
{% load static %}

<div class="dz-bnr-inr style-1 dz-bnr-inr-sm">
    <div class="container">
        <div class="dz-bnr-inr-entry">
            <h1>{{page_title}}</h1>
            <!-- Breadcrumb Row -->
            <nav aria-label="breadcrumb" class="breadcrumb-row">
                <ul class="breadcrumb">
                    <li class="breadcrumb-item" style="color:var(--secondary);"><a href="{% url 'w3music:index' %}">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">{{page_title}}</li>
                </ul>
            </nav>
            <!-- Breadcrumb Row End -->
        </div>
    </div>
</div>

templates/w3music/elements/footer-1.html
{% load static %}

	<footer class="site-footer style-1 bg-dark" id="footer">
		<div class="footer-top">
			<div class="container-fluid">
				<div class="row">
					<div class="col-xl-12">
						<div class="text-center mid-content">
							<span class="sub-footer-title wow fadeInUp" data-wow-delay="0.6s">Want  to work together?</span>
							<h2 class="footer-title wow fadeInUp" data-wow-delay="0.8s">exapl@gmail.com</h2>
						</div>
						<div class="footer-menu  wow fadeInUp" data-wow-delay="1s">
							<ul class="">
								<li><a href="{% url 'w3music:index' %}">Start Here</a></li>
								<li><a href="{% url 'w3music:events' %}">Events</a></li>
								<li><a href="{% url 'w3music:blog-details' %}">Blog</a></li>
								<li><a href="{% url 'w3music:contact-us' %}">Contact Us</a></li>
							</ul>	
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Footer Bottom Part -->
		<div class="container-fluid">
			<div class="footer-bottom">
				<div class="row justify-content-center">
					<div class="col-lg-4 col-md-6 col-sm-6 text-md-start m-b10">
						<span class="text">@<span class="current-year">2024</span><a href="https://dexignzone.com/" target="_blank"> Dexignzone.com</a></span>
					</div>
					<div class="col-lg-4 col-md-6 col-sm-6 text-md-center m-b10">
						<span class="copyright-text">Made with in <a href="https://dexignzone.com/" target="_blank">Dexignzone.com</a></span>
					</div>
					<div class="col-lg-4 col-md-6 col-sm-6 text-md-center text-lg-end text-center m-b10">
						<span class="text">Go to top <i class="fa-solid fa-arrow-up"></i></span>
					</div>
				</div>
			</div>
		</div>
	</footer>

templates/w3music/elements/footer-2.html
{% load static %}

	<footer class="site-footer style-2 bg-dark" id="footer">
		<div class="footer-top">
			<div class="container">
				<div class="row">
					<div class="col-xl-6 col-lg-6  col-md-12">
						<div class="footer-logo">
							<a href="{% url 'w3music:index' %}" class="logo-white"><img src="{% static 'w3music/images/logo-white.png' %}" alt="/"></a>
						</div>
						<h2 class="footer-title">We Develop & Create Music <span>Platforms</span></h2>
					</div>
					<div class="col-xl-4 col-lg-4 col-md-12">
							<h6 class="footer-subtitle">Address</h6>
							<p class="text"><span>Germany</span> 785 15h Street, Office 478 Berlin, De 81566</p>	
						<div class="dz-social-icon style-1 dz-hover-move white m-b30">
							<ul>									
								<li style="transform: translate(0px, 0px) scale(1);">
									<a target="_blank" href="https://www.facebook.com/dexignzone/">
										<i class="fab fa-facebook-f"></i>
									</a>
								</li>
								<li style="transform: translate(-0.1px, 0px) scale(1);">
									<a target="_blank" href="https://twitter.com/dexignzones">
										<i class="fab fa-twitter"></i>
									</a>
								</li>
								<li style="transform: translate(0px, 0px) scale(1);">
									<a target="_blank" href="https://www.instagram.com/dexignzone/">
										<i class="fab fa-instagram"></i>
									</a>
								</li>
								<li style="transform: translate(0px, 0px) scale(1);">
									<a target="_blank" href="https://www.youtube.com/channel/UCGL8V6uxNNMRrk3oZfVct1g">
										<i class="fab fa-youtube"></i>
									</a>
								</li>
							</ul>
						</div>
					</div>
					<div class="col-xl-2 col-lg-2 col-md-12">
						<h6 class="footer-subtitle">Say Hello</h6>
						<span class="infogmail">Demo@gmail.com</span>
						<span class="number">+1012 3456 789</span>
					</div>
				</div>
			</div>
		</div>
		<!-- Footer Bottom Part -->
		<div class="container">
			<div class="footer-bottom">
				<div class="row">
					<div class="col-xl-8 col-lg-7 col-md-12">
						<div class="footer-menu">
							<ul class="">
								<li class="active"><a href="{% url 'w3music:index' %}">Home</a></li>
								<li><a href="{% url 'w3music:about-us' %}">About</a></li>
								<li><a href="{% url 'w3music:services' %}">Services</a></li>
								<li><a href="{% url 'w3music:events' %}">Events</a></li>
								<li><a href="{% url 'w3music:blog-details' %}">Blog</a></li>
								<li><a href="{% url 'w3music:contact-us' %}">Contact us</a></li>
							</ul>
						</div>
					</div>
					<div class="col-xl-4 col-lg-5 col-md-12 text-lg-end">
						<span class="copyright-text"><a href="https://dexignzone.com/" target="_blank">Dexignzone</a> © <span class="current-year">2024</span>. All Rights Reserved.</span>
					</div>
				</div>
			</div>
		</div>
	</footer>

templates/w3music/elements/footer-3.html
{% load static %}

	<footer class="site-footer style-3 bg-dark" id="footer">
		<div class="footer-top">
			<div class="container">
				<div class="row text-xl-start">
					<div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 m-b20">
						<div class="footer-logo">
							<a href="{% url 'w3music:index' %}" class="logo-white"><img src="{% static 'w3music/images/logo-white.png' %}" alt="/"></a>
						</div>
						<p class="text">Velit egestas dui id ornare arcu. Nibh sit amet commodo nulla nullam vehicula. Arcu dictum varius duis at consectetur. Faucibus nisl tincidunt eget nullam facilisis gravida neque.</p>
					</div>
					<div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 m-b20">
						<h6 class="footer-title">Office</h6>
						<p class="text"><span>Germany</span> 785 15h Street, Office 478 Berlin, De 81566</p>
						<span class="infogmail"><a href="javascript:void(0)">Demo@gmail.com</a></span>
						<span class="number"><a href="tel:+001234567890">+00 123 456 7890</a></span>
					</div>
					<div class="col-xl-2 col-lg-6 col-md-6 col-sm-12 m-b20">
						<h6 class="footer-title">Links</h6>
						<div class="footer-menu">
							<ul class="">
								<li><a href="{% url 'w3music:index' %}">Home</a></li>
								<li><a href="{% url 'w3music:about-us' %}">About</a></li>
								<li><a href="{% url 'w3music:services' %}">Services</a></li>
								<li><a href="{% url 'w3music:events' %}">Events</a></li>
								<li><a href="{% url 'w3music:blog-details' %}">Blog</a></li>
								<li><a href="{% url 'w3music:contact-us' %}">Contact us</a></li>
							</ul>	
						</div>
					</div>			
					<div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 m-b20">
						<h6 class="footer-title">Newsletter</h6>
						<form class="dzSubscribe dz-subscribe-wrapper1" action="" method="">
							<div class="dzSubscribeMsg"></div>
							<div class="form-group">
								<div class="input-group">
									<i class="fa-regular fa-envelope"></i>
									<input name="dzEmail" required="required" type="email" class="form-control" placeholder="Enter Your Email Address">
									<div class="input-group-addon ">
										<button name="submit" value="Submit" type="submit" class="btn-link">
											<i class="la la-arrow-right"></i>
										</button>
									</div>
								</div>
							</div>
							<div class="form-check">
								<input class="form-check-input checkbox-secondary m-r15" type="checkbox" id="footer_check" value="">
								<label class="form-check-label" for="footer_check">I Agree To The <span><a href="javascript:void(0)">Privacy Policy</a></span></label>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
		<!-- Footer Bottom Part -->
		<div class="container">
			<div class="footer-bottom">
				<div class="row justify-content-between align-items-center">
					<div class="text-center text-xl-start col-xl-6">
						<span class="copyright-text"><a href="https://dexignzone.com/" target="_blank">Dexignzone</a> © <span class="current-year">2024</span>. All Rights Reserved.</span>
					</div>
					<div class="text-center text-xl-end col-xl-6">
						<div class="dz-social-icon">
							<ul>									
								<li>
									<a target="_blank" href="https://www.facebook.com/dexignzone/">
										<i class="fab fa-facebook-f"></i>
									</a>
								</li>
								<li>
									<a target="_blank" href="https://twitter.com/dexignzones">
										<i class="fab fa-twitter"></i>
									</a>
								</li>
								<li>
									<a target="_blank" href="https://www.instagram.com/dexignzone/">
										<i class="fab fa-instagram"></i>
									</a>
								</li>
								<li>
									<a target="_blank" href="https://www.youtube.com/channel/UCGL8V6uxNNMRrk3oZfVct1g">
										<i class="fab fa-youtube"></i>
									</a>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</footer>

templates/w3music/elements/footer.html
{% load static %}

	<footer class="site-footer style-3 bg-dark" id="footer">
		<div class="footer-top">
			<div class="container">
				<div class="row text-xl-start">
					<div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 m-b20">
						<div class="footer-logo">
							<a href="{% url 'w3music:index' %}" class="logo-white"><img src="{% static 'w3music/images/logo-white.png' %}" alt="/"></a>
						</div>
						<p class="text">Velit egestas dui id ornare arcu. Nibh sit amet commodo nulla nullam vehicula. Arcu dictum varius duis at consectetur. Faucibus nisl tincidunt eget nullam facilisis gravida neque.</p>
					</div>
					<div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 m-b20">
						<h6 class="footer-title">Office</h6>
						<p class="text">Germany 785 15h Street, Office 478 Berlin, De 81566</p>
						<span class="infogmail"><a href="javascript:void(0)">Demo@gmail.com</a></span>
						<span class="number"><a href="tel:+001234567890">+00 123 456 7890</a></span>
					</div>
					<div class="col-xl-2 col-lg-6 col-md-6 col-sm-12 m-b20">
						<h6 class="footer-title">Links</h6>
						<div class="footer-menu">
							<ul class="">
								<li><a href="{% url 'w3music:index' %}">Home</a></li>
								<li><a href="{% url 'w3music:about-us' %}">About</a></li>
								<li><a href="{% url 'w3music:services' %}">Services</a></li>
								<li><a href="{% url 'w3music:events' %}">Events</a></li>
								<li><a href="{% url 'w3music:blog-details' %}">Blog</a></li>
								<li><a href="{% url 'w3music:contact-us' %}">Contact us</a></li>
							</ul>	
						</div>
					</div>			
					<div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 m-b20">
						<h6 class="footer-title">Newsletter</h6>
						<form class="dzSubscribe dz-subscribe-wrapper1" action="" method="">
							<div class="dzSubscribeMsg"></div>
							<div class="form-group">
								<div class="input-group">
									<i class="fa-regular fa-envelope"></i>
									<input name="dzEmail" required="required" type="email" class="form-control" placeholder="Enter Your Email Address">
									<div class="input-group-addon ">
										<button name="submit" value="Submit" type="submit" class="btn-link">
											<i class="la la-arrow-right"></i>
										</button>
									</div>
								</div>
							</div>
							<div class="form-check">
								<input class="form-check-input checkbox-secondary m-r15" type="checkbox" id="footer_check" value="">
								<label class="form-check-label" for="footer_check">I Agree To The <span><a href="javascript:void(0)">Privacy Policy</a></span></label>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
		<!-- Footer Bottom Part -->
		<div class="container">
			<div class="footer-bottom">
				<div class="row justify-content-between align-items-center">
					<div class="text-center text-xl-start col-xl-6">
						<span class="copyright-text"><a href="https://dexignzone.com/" target="_blank">Dexignzone</a> © <span class="current-year">2024</span>. All Rights Reserved.</span>
					</div>
					<div class="text-center text-xl-end col-xl-6">
						<div class="dz-social-icon">
							<ul>									
								<li>
									<a target="_blank" href="https://www.facebook.com/dexignzone/">
										<i class="fab fa-facebook-f"></i>
									</a>
								</li>
								<li>
									<a target="_blank" href="https://twitter.com/dexignzones">
										<i class="fab fa-twitter"></i>
									</a>
								</li>
								<li>
									<a target="_blank" href="https://www.instagram.com/dexignzone/">
										<i class="fab fa-instagram"></i>
									</a>
								</li>
								<li>
									<a target="_blank" href="https://www.youtube.com/channel/UCGL8V6uxNNMRrk3oZfVct1g">
										<i class="fab fa-youtube"></i>
									</a>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</footer>

templates/w3music/elements/preloader-2.html
{% load static %}
<div id="loading-area3" class="loading-page-2">
	<span class="text">W3MUSIC</span>
</div> 

templates/w3music/elements/preloader-3.html
{% load static %}
<div id="loading-area2" class="loading-page-1">
	<div class="load-text">
		<span data-text="W" class="text-load">W</span>
		<span data-text="3" class="text-load">3</span>
		<span data-text="M" class="text-load">M</span>
		<span data-text="U" class="text-load">U</span>
		<span data-text="S" class="text-load">S</span>
		<span data-text="I" class="text-load">I</span>
		<span data-text="C" class="text-load">C</span>
	</div>
</div> 

templates/w3music/elements/preloader-4.html
{% load static %}
<div id="loading-area-4" class="loading-page-4">
	<div class="loading-inner">
		<div class="loader"></div>
		<div class="loder-section left-section"></div>
		<div class="loder-section right-section"></div>
	</div>
</div>

templates/w3music/elements/preloader.html
{% load static %}
<div id="loading-area" class="loading-page-3">
	<img src="{% static 'w3music/images/loading.gif' %}" alt="">
</div> 